
esp32:
  variant: ESP32C3
  board: adafruit_qtpy_esp32c3
  framework:
    type: arduino

esphome:
  name: "nexus433"
  platformio_options:
    lib_deps:
      - https://github.com/FreeBear-nc/arduino-nexus433.git
    # Most other boards will have BUILTIN_LED defined
    # but not the Adafruit QT Py ESP32-C3.
    # The ESP32-C3 Super Mini uses gpio08 for both the
    # builtin LED and the onboard WS2812.
    build_flags: -DBUILTIN_LED=8 

external_components:
  - source:
      type: local
      path: components
    components:
      - nexus433
    refresh: always

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  manual_ip:
    static_ip: !secret ip_address
    gateway: !secret gateway
    subnet: 255.255.255.0
  power_save_mode: "light"
  output_power: 8.5dB

preferences:
  flash_write_interval: 3600min

logger:

api:
  reboot_timeout: 0s

ota:
  platform: esphome

mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_username
  password: !secret mqtt_password

nexus433:
  id: mqttnexus433
  pin: 4

